version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: jobal
      POSTGRES_PASSWORD: jobalpass
      POSTGRES_DB: jobaldb
    ports:
      - "5432:5432"
    volumes:
      - jobal-db-data:/var/lib/postgresql/data
volumes:
  jobal-db-data: 